<x-app-layout><x-dashboard.sidebar><x-alert-information /><x-samsat-modal />
<div class="ip-page">
    <header class="ip-page-header"><div><p class="ip-kicker">Operasional</p><h1 class="ip-title">Armada & Samsat</h1><p class="ip-subtitle">Pantau kendaraan dan masa berlaku dokumen tanpa alur administrasi yang rumit.</p></div>@can('createarmada')<a href="{{ route('armada.create') }}" class="ip-btn-primary">+ Tambah kendaraan</a>@endcan</header>
    <div class="grid gap-4 sm:grid-cols-3">
        <a href="{{ route('armada.index',['document_status'=>'overdue']) }}" class="group rounded-2xl border border-red-200 bg-gradient-to-br from-red-50 to-white p-5 shadow-sm hover:-translate-y-0.5"><p class="text-[11px] font-extrabold uppercase tracking-wider text-red-600">Terlambat</p><p class="mt-3 text-3xl font-extrabold text-red-700">{{ $stats['overdue'] }}</p><p class="mt-1 text-xs text-red-500">Perlu ditangani sekarang</p></a>
        <a href="{{ route('armada.index',['document_status'=>'due_soon']) }}" class="group rounded-2xl border border-amber-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm hover:-translate-y-0.5"><p class="text-[11px] font-extrabold uppercase tracking-wider text-amber-600">Jatuh tempo &le; 30 hari</p><p class="mt-3 text-3xl font-extrabold text-amber-700">{{ $stats['due_soon'] }}</p><p class="mt-1 text-xs text-amber-600">Siapkan perpanjangan</p></a>
        <a href="{{ route('armada.index',['document_status'=>'safe']) }}" class="group rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-50 to-white p-5 shadow-sm hover:-translate-y-0.5"><p class="text-[11px] font-extrabold uppercase tracking-wider text-emerald-600">Dokumen aman</p><p class="mt-3 text-3xl font-extrabold text-emerald-700">{{ $stats['safe'] }}</p><p class="mt-1 text-xs text-emerald-600">Belum perlu tindakan</p></a>
    </div>
    <form class="ip-card flex gap-3 p-4"><input name="search" value="{{ $search }}" placeholder="Cari nama kendaraan, nomor polisi, atau merek" class="ip-input flex-1"><button class="ip-btn-dark">Cari</button></form>
    <div class="ip-card"><div class="ip-table-wrap"><table class="ip-table min-w-[940px]"><thead><tr><th>Kendaraan</th><th>Lokasi / PIC</th><th>Status kendaraan</th><th>Status Samsat</th><th>Berlaku sampai</th><th class="text-right">Aksi</th></tr></thead><tbody>@forelse($armadas as $armada)@include('armada._rows',['armadas'=>collect([$armada])])@empty<tr><td colspan="6" class="py-14 text-center text-slate-500">Belum ada kendaraan.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-200 p-4">{{ $armadas->links() }}</div></div>
</div>
<script>function openSamsatModal(id){const form=document.getElementById('samsatForm');form.action=@json(url('/armada'))+'/'+id+'/samsat';const modal=document.getElementById('samsatModal');modal.classList.remove('hidden');modal.classList.add('flex')}function closeSamsatModal(){const modal=document.getElementById('samsatModal');modal.classList.add('hidden');modal.classList.remove('flex')}</script>
</x-dashboard.sidebar></x-app-layout>
