<x-app-layout><x-dashboard.sidebar><x-alert-information /><x-samsat-modal />
<div class="mx-auto max-w-6xl space-y-6">
    <header class="relative overflow-hidden rounded-[1.75rem] bg-gradient-to-br from-sky-700 via-sky-800 to-slate-950 p-6 text-white shadow-xl dark:from-[#11151e] dark:via-[#0b0c0f] dark:to-black sm:p-8"><div class="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-sky-300/20 blur-3xl dark:bg-red-600/25"></div><div class="relative flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p class="text-[11px] font-extrabold uppercase tracking-[.22em] text-sky-200 dark:text-red-400">{{ $armada->type }} &middot; {{ $armada->year }}</p><h1 class="mt-2 text-2xl font-extrabold sm:text-3xl">{{ $armada->name }}</h1><p class="mt-2 text-sm text-sky-100/75 dark:text-slate-400">{{ $armada->nomor_polisi }} &middot; {{ $armada->brand }} {{ $armada->model }}</p></div><div class="flex flex-wrap gap-2"><x-status-badge :status="$armada->document_status" />@can('samsatarmada')<button onclick="openSamsatModal({{ $armada->id }})" class="ip-btn bg-sky-500 text-white hover:bg-sky-400 dark:bg-red-600 dark:hover:bg-red-700">Catat perpanjangan</button>@endcan @can('editarmada')<a href="{{ route('armada.edit',$armada) }}" class="ip-btn bg-white text-slate-950">Edit kendaraan</a>@endcan</div></div></header>

    <div class="grid gap-6 lg:grid-cols-[1fr,390px]">
        <section class="ip-card ip-card-body"><div class="flex items-center justify-between"><div><p class="ip-kicker">Kendaraan</p><h2 class="mt-1 ip-section-title">Data operasional</h2></div><x-status-badge :status="$armada->status" /></div><dl class="mt-6 grid gap-5 sm:grid-cols-2">@foreach(['Lokasi'=>$armada->location?->name,'Penanggung jawab'=>$armada->user?->name,'Nomor rangka'=>$armada->nomor_rangka,'Nomor mesin'=>$armada->nomor_mesin] as $label=>$value)<div><dt class="text-[10px] font-extrabold uppercase tracking-wide text-slate-400">{{ $label }}</dt><dd class="mt-1 font-bold text-slate-800">{{ $value ?: '-' }}</dd></div>@endforeach</dl></section>
        <section class="rounded-2xl border border-sky-100 bg-gradient-to-br from-sky-50 to-white p-5 shadow-soft dark:border-white/10 dark:from-[#11151e] dark:to-[#0b0c0f]"><p class="ip-kicker">Samsat</p><div class="mt-3 flex items-center justify-between gap-3"><h2 class="text-lg font-extrabold text-slate-950 dark:text-white">Masa berlaku STNK</h2><x-status-badge :status="$armada->document_status" /></div><p class="mt-6 text-3xl font-extrabold tracking-tight text-slate-950 dark:text-white">{{ optional($armada->stnk_expired)->translatedFormat('d M Y') ?: '-' }}</p><p class="mt-2 text-xs font-semibold text-slate-500">Gunakan “Catat perpanjangan” setelah proses Samsat selesai.</p>@if($armada->stnk_attachment)<a href="{{ route('armada.stnk.attachment',$armada) }}" class="mt-5 inline-flex text-sm font-extrabold text-sky-700 dark:text-red-400">Unduh dokumen terbaru &rarr;</a>@endif</section>
    </div>

    <section class="ip-card"><div class="border-b border-slate-100 px-5 py-4"><p class="ip-kicker">Riwayat</p><h2 class="mt-1 ip-section-title">Perpanjangan STNK</h2></div><div class="ip-table-wrap"><table class="ip-table min-w-[760px]"><thead><tr><th>Diproses</th><th>Berlaku lama</th><th>Berlaku baru</th><th class="text-right">Biaya</th><th>Dicatat oleh</th><th class="text-right">Bukti</th></tr></thead><tbody>@forelse($armada->renewals->sortByDesc('processed_at') as $renewal)<tr><td>{{ $renewal->processed_at->format('d/m/Y') }}</td><td>{{ optional($renewal->previous_expired_at)->format('d/m/Y') ?: '-' }}</td><td class="font-extrabold text-slate-900">{{ $renewal->new_expired_at->format('d/m/Y') }}</td><td class="text-right font-bold">Rp {{ number_format($renewal->cost,0,',','.') }}</td><td>{{ $renewal->creator?->name }}</td><td class="text-right">@if($renewal->attachment)<a href="{{ route('armada.renewals.attachment',[$armada,$renewal]) }}" class="font-bold text-red-600">Unduh</a>@else - @endif</td></tr>@empty<tr><td colspan="6" class="py-12 text-center text-slate-500">Belum ada riwayat perpanjangan.</td></tr>@endforelse</tbody></table></div></section>
</div>
<script>function openSamsatModal(id){const form=document.getElementById('samsatForm');form.action=@json(url('/armada'))+'/'+id+'/samsat';const modal=document.getElementById('samsatModal');modal.classList.remove('hidden');modal.classList.add('flex')}function closeSamsatModal(){const modal=document.getElementById('samsatModal');modal.classList.add('hidden');modal.classList.remove('flex')}</script>
</x-dashboard.sidebar></x-app-layout>
